# Generated by Django 5.2.4 on 2025-10-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='message',
            field=models.TextField(default='U r welcome'),
        ),
    ]
